In [28]:
import pandas as pd 
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RepeatedKFold
import matplotlib.pyplot as plt
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix,multilabel_confusion_matrix,roc_auc_score,roc_curve,auc,ConfusionMatrixDisplay,precision_score,recall_score

In [3]:
x_train_all=pd.read_csv("CompleteDataSet/x_train_all.csv")
y_train_all=pd.read_csv("CompleteDataSet/y_train_all.csv")
x_test_all=pd.read_csv("CompleteDataSet/x_test_all.csv")
y_test_all=pd.read_csv("CompleteDataSet/y_test_all.csv")

### Metrics

In [29]:
def metric(Y_test,predicted):   
    accuracy = accuracy_score(Y_test,predicted )
    f1 = f1_score(predicted, Y_test, average="weighted")
    conf_matrix = confusion_matrix(predicted, Y_test)
    precision = precision_score(Y_test, predicted, average="weighted",zero_division=1)
    recall = recall_score(Y_test, predicted, average="weighted")

    # Y_test_bin = label_binarize(Y_test, classes=[0, 1, 2,3,4,5,6,7,8,9])
    # roc = roc_auc_score(Y_test_bin, predicted_probs, multi_class="ovr", average="weighted")

    conf_matrices = multilabel_confusion_matrix(Y_test, predicted)
    tp = conf_matrices[:,1,1]
    fp = conf_matrices[:,0,1]
    tn = conf_matrices[:,0,0]
    fn = conf_matrices[:,1,0]
    # fpr = (fp/(tn + fp), tp + fn)
    tnr = (tn/(tn + fp), tp + fn)

    # fpr, tpr, _ = roc_curve(Y_test_bin.ravel(), predicted_probs.ravel())


    # auc_val = auc(fpr, tpr)
    # plt.figure()
    # plt.plot(fpr, tpr, color='darkorange', lw=2, label='AUC (area = %0.2f)' % auc_val)
    # plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    # plt.xlabel('False Positive Rate')
    # plt.ylabel('True Positive Rate')
    # plt.title('ROC Curve')
    # plt.legend(loc="lower right")
    # plt.show()

    # out=ConfusionMatrixDisplay(conf_matrix,display_labels=gnb.classes_)
    # out.plot()
    # plt.show()
    print("Accuracy:", accuracy)
    print("F1 Score:", f1)
    print("Precision:", precision)
    print("Recall/Sensitivity/True Positive Rate:", recall)
    print("Specificity:", tnr)
    # print("False Positive Rate:", fpr)
    # print("Area under ROC curve:", roc)
    print("Confusion Matrix:\n", conf_matrix)


### Cross Validation

In [4]:
from sklearn.model_selection import KFold 


In [5]:
def kfold_10(input,output):
    kf = KFold(n_splits=10) 
    dt_classifier = DecisionTreeClassifier()
    accuracy_scores = []
    for train_index, test_index in kf.split(input):
        print("Train:", len( train_index), "Validation:",len(test_index))
        X_train, X_test = input.iloc[train_index], input.iloc[test_index] 
        y_train, y_test = output.iloc[train_index], output.iloc[test_index]
        dt_classifier.fit(X_train, y_train)
        pred=dt_classifier.predict(X_test)
        accuracy = accuracy_score(y_test, pred)
        accuracy_scores.append(accuracy)
    average_accuracy = sum(accuracy_scores) / 10

    print(f"Average Accuracy: {average_accuracy}")



In [6]:
x_train_all.shape

(9690, 2304)

In [7]:
y_train_all.shape

(9690, 1)

In [8]:
kfold_10(x_train_all,y_train_all)

Train: 8721 Validation: 969
Train: 8721 Validation: 969
Train: 8721 Validation: 969
Train: 8721 Validation: 969
Train: 8721 Validation: 969
Train: 8721 Validation: 969
Train: 8721 Validation: 969
Train: 8721 Validation: 969
Train: 8721 Validation: 969
Train: 8721 Validation: 969
Average Accuracy: 0.4893704850361197


In [32]:
def train_test_split(X_train,X_test,y_test,y_train):
    dt_classifier = DecisionTreeClassifier()
    dt_classifier.fit(X_train,y_train)
    pred=dt_classifier.predict(X_test)
    accuracy = accuracy_score(y_test, pred)
    metric(y_test,pred)
    print("The Accuracy is:",accuracy)

In [33]:
train_test_split(x_train_all,x_test_all,y_test_all,y_train_all)

Accuracy: 0.6851132686084143
F1 Score: 0.6881416018187559
Precision: 0.6830429990865233
Recall/Sensitivity/True Positive Rate: 0.6851132686084143
Specificity: (array([0.98316832, 0.90168776, 0.91282051, 0.95265152, 0.91934156,
       0.98910891, 0.98566667, 0.98976898, 0.98809524, 0.99266667]), array([ 60, 720, 750, 450, 660,  60,  90,  60, 150,  90], dtype=int64))
Confusion Matrix:
 [[ 18  19   1   2  22   0   1   0   6   0]
 [ 10 557  71  24  58   0  10  23  18  19]
 [  7  61 566  63  30   1   5   6  16  15]
 [  3   9  41 308  39   7  10   1  14   1]
 [ 17  60  57  27 473  23   1   0  11   0]
 [  0   0   4   0   7  29   8   9   3   2]
 [  3   2   1  12  11   0  40   3  11   0]
 [  2   5   6   4   7   0   0  15   6   1]
 [  0   4   1   5   6   0  14   0  64   5]
 [  0   3   2   5   7   0   1   3   1  47]]
The Accuracy is: 0.6851132686084143
